### ISSUE TITLE
The regional example has a component containing a separator

### ISSUE THREAD

**Issue by nfirvine** [wtcross/simple-naming-scheme#1]
`acme-billing-dev-api-us-east-1` does not conform to `<company>-<app>-<env>-<role>-<location>-<index>` because `us-east` contains a hyphen itself. The grammar is ambiguous. Suggest it could be `acme-billing-dev-api-useast-1`.

**Comment by wtcross** [comment]
This is a good reason why I need to change the example. Currently it only demonstrates easily readable names that cannot be consistently parsed. That said, I'll make the document more clearly define the grammar. Thanks @nfirvine

**Comment by wtcross** [comment]
I'm going to clean up the doc so that it is clear the names aren't necessarily non-ambiguous. Here are some reasons:
- it's rare that a name needs to be parseable
- if you can access a named thing then you can probably access the properties that are part of the name (aws resources, for example)
- names are useful if they are easy to construct during automation and when they are easy to read in consoles and things'

Thank you for the issue submission, it helped clarify what I need to do in order to simplify the doc.

**Comment by nfirvine** [comment]
Cool, thanks. I for one would make my names parseable, but I'm anal. :)
